### ISSUE TITLE
Machine Learning Technique

### ISSUE THREAD

**Issue by CindyFMX** [kudrikmed/SkinTypeClassification#1]
Hello, may I know which machine learning technique you applied and the accuracy? Do you have a documentation on your development?

**Comment by kudrikmed** [comment]
Hello! CNN using Keras. Documentation is coming soon)

**Comment by CindyFMX** [comment]
I see, by the way I try to find your dataset but I cannot find it. May I know where do you store?

**Comment by kudrikmed** [comment]
If You have some difficulties with data under dvc, I've added a direct link to dataset in readme.md. Please, see it (№ 4 in `Reproduce learning process` part)
